### ISSUE TITLE
reply message should not be the entire payload

### ISSUE THREAD

**Issue by laroque** [project8/dripline#118]
There may be times when a return code indicates a warning and so a return-msg is warranted, but a valid result is also present. As such, a 'return-msg' field should be used. This being the case, all exceptions/errors should put their message into that field for consistency. We'll need to update the wire protocol to reflect these. I should also abstract away the payload formatting to reflect our standards (and this too should be explicit in the wire protocol).

**Comment by laroque** [comment]
Okay, wire-protocol decision made, it is going to be its own field. There isn't an obvious way to name it in a consistent way. retmsg is probably closest but I think I prefer something more spelled out

**Comment by nsoblath** [comment]
After slightly more discussion on Slack, `return_msg` to be more consistent with other uses of the underscore.

**Comment by laroque** [comment]
Okay, in the case of a reply message, if the payload is not a dict, the value is dumped into payload.values[<value>]
