### ISSUE TITLE
send_request should make use of the async backend

### ISSUE THREAD

**Issue by laroque** [project8/dripline#135]
**WARNING!...** this isn't actually a starter project, it is kind of advanced.

Currently the sending a request involves using threading and a new connection to send a message and get a reply. This feels super dirty. I'd like to do something like:

``` python
timeout_time = datetime.datetime.now() + datetime.timedelta(seconds=timeout_in_seconds)
correlation_id = uuid.uuid4()
self.send_message(<your request message stuff>, correlation_id=correlation_id)
while self._results[correlation_id] is None and datetime.datetime.now < timeout_time:
     #some yielding block that lets the service process any new messages
```

... but I haven't got a solution for the yielding code block

should just send a request and then watch some local dictionary of responses for one with a matched correlation_id... need to have solutions to two issues:
1) still need to support timeout for getting the reply
2) need to make sure data-structures don't grow without bound if either replies collect but never get sent anywhere, or records of replies awaiting with reply do not grow similarly

**Comment by laroque** [comment]
ugh... why do I keep doing this to myself, the send_request method of service is blocking, which means that it cannot then handle_reply because it is still trying to send_request.... python 3's yield from syntax may offer a nice solution to this, I'll play with pika 0.10 and python 3.4 at some point, but for now I should give up

**Comment by guiguem** [comment]
This issue was moved to project8/dripline-python#3
