### ISSUE TITLE
Inheritance of broker knowledge

### ISSUE THREAD

**Issue by wcpettus** [project8/dripline#161]
Classes that use Interface (or will soon use it) to communicate with other endpoints (ESR, RSA,...) have no mechanism to natively know the broker.  This currently requires doubly-defining the broker in config file - both at Spimescape level and at the specific module level (ESR_Measurement, RSAAcquisitionInterface,...).

As we cleanup the dragonfly methodology to use Interface more (and not repeatedly using Service and Message to define RequestMessage and send_request), we should update this issue with the known instances.

When this issue gets resolved, the errant config files should get cleaned.

**Comment by laroque** [comment]
See dripline issue #162. The solution is that classes should not use interface, the desired methods should be made available to endpoints via their providers (ie ported into the `Provider` class).

**Comment by laroque** [comment]
@wcpettus: I believe this issue can be closed as no longer relevant
