### ISSUE TITLE
Setting power supply times out

### ISSUE THREAD

**Issue by mwachtendonk** [project8/dripline#50]
$source /home/project8/python_environments/dripline/bin/activate
$open_spimescape_portal -vvv -c /home/project8/SlowControl/wolfburn.yaml

New terminal:
$source /home/project8/python_environments/dripline/bin/activate
$dripline_agent -vvv -b myrna.local set current_limit_bath 0.5
I've also tried 
$dripline_agent -vvv -b mynra.local set current_output_status_bath ON/OFF

with the same results

**Comment by laroque** [comment]
fixed as of commit 6be3f4709f031
