### ISSUE TITLE
Provider needs to throw error on bad endpoint implementation

### ISSUE THREAD

**Issue by mgrants** [project8/dripline#59]

**Comment by laroque** [comment]
Actually should maybe be done by open_spimescape_portal.... add_endpoint should have failed and errored

**Comment by laroque** [comment]
I remember that this happened, but I've completely forgotten how to reproduce this. Does anyone remember the details of what was going on?

**Comment by laroque** [comment]
I have no idea how to reproduce this so I'm closing it... It probably isn't fixed if someone wants to reopen with more information.
