### ISSUE TITLE
USB/serial support

### ISSUE THREAD

**Issue by laroque** [project8/dripline#81]
It would be good to use the alicat to keep an eye on LHe boiloff. That requires talking to a serial device (presumably over usb). USB support would also let us integrate the frequency counter or even the RGA (though you'd have to do a lot of convincing to on the latter for me to think it worth the effort). This would also in principle give us access to the MCA without ORCA, though loading the FPGA correctly and decoding things may make that difficult regardless.

**Comment by wcpettus** [comment]
Closing issue because:
- if implemented, this is a dragonfly problem
- we don't plan to ever implement USB for stability reasons
