### ISSUE TITLE
when an endpoint raises a not-implemented, it should make it back to the whoever sent the request

### ISSUE THREAD

**Issue by grybka** [project8/dripline#90]
If i try and "send multiplexer '*OPC?' " I get None back, rather than not-implemented error

**Comment by laroque** [comment]
Would change NotImplemented to something that inherits from DriplineException fix this? I should check.

**Comment by laroque** [comment]
I've checked, this works if I use a DriplineInternalError(). I should create a new exception value 3xx named DriplineUnsupportedMethod, that is used in the endpoint's raiser with something like "<class_name> does not support <method_name>"... will do this once 1.6.3 tagging is cleaned up.

**Comment by laroque** [comment]
resolved in 158f98d
